### ISSUE TITLE
Pourquoi ces composants jQuery ? 

### ISSUE THREAD

**Issue by atomrc** [MaitreManuel/Messy#1]
Tout d'abord beau projet, il semble que tu as bien compris les principes de `React` :)

Tu as juste un problème, je me demande bien pourquoi tes composants d'overlay et de loaders ne sont pas des composants `React` ? (cf https://github.com/MaitreManuel/Messy/blob/e8e8bd88842506b2fbed0bde49c46b046849b526/js/spin.js)

C'est trop dommage tout le reste de ton code est bien séparé en composants mais cette partie est un sac de nœuds fortement lié à la structure du DOM (ton application peut être complètement par terre si la structure de ton DOM change).  
Et ça te force à faire des query du `DOM` dans ton appli `React` (cf https://github.com/MaitreManuel/Messy/blob/1936af84bc6d21684ebc21e24498e6368718a20f/src/components/Message.js#L115) ce qui rend ton appli liée au DOM et donc impossible à rendre côté serveur. 

Garde en tête que normalement dans une application `React` tu ne doit faire qu'une unique requête au `DOM`, celle pour récupérer le conteneur de ton app

```javascript
ReactDOM.render(<App />, document.getElementById("main"))
```

Si tu utilises ailleurs dans ton code `document` ou des sélecteurs `css`, tu as un problème :)

**Comment by MaitreManuel** [comment]
Merci beaucoup !

Et vous avez exactement raison pour l'overlay et le spinner, j'y avais pas du tout pensé a le faire sur le coup (alors que le but du projet c'est quand même les composants React xD) et oui du coup ce JQuery pour l'overlay c'est le cheat pour contourner le problème que ce soit mis en dur sur le DOM, car avant j'avais mis la fonction dans un fichier à part et du coup impossible de faire un callback pour recharger les messages sans recharger la page entièrement (je faisais un vieux window.location.reload) ça ne me plaisais pas.

Donc une mise à jour en plus de ce que j'ai prévue de faire prochainement !

**Comment by MaitreManuel** [comment]
Et voilà c'est réglé (en plus mon ancienne solution JQuery créé un bug, c'est-à-dire que ça ajouté la fonction a celle déjà existante donc si on envoyait des messages à la suite sans refresh la page ça donnait ça => 1er message publié 1 fois, 2em message publié 2 fois, 3èm 3 fois, etc...)!
